// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP6XPpv4xcihfLySJubR7MnK4lIdQ9zIk',
    appId: '1:429952031766:web:4248ba73683f135e586937',
    messagingSenderId: '429952031766',
    projectId: 'mealrecipes-mobileapp-ccc8a',
    authDomain: 'mealrecipes-mobileapp-ccc8a.firebaseapp.com',
    storageBucket: 'mealrecipes-mobileapp-ccc8a.firebasestorage.app',
    measurementId: 'G-GS8PN64P4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqnvh6bAW5RW57R693KA-iIc3V3j4ktjY',
    appId: '1:429952031766:android:dfaf78086a1bb9b5586937',
    messagingSenderId: '429952031766',
    projectId: 'mealrecipes-mobileapp-ccc8a',
    storageBucket: 'mealrecipes-mobileapp-ccc8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUsZ1mXEe5pVqeFFv_kfx7A8eCgsLu8-Q',
    appId: '1:429952031766:ios:73b49f338f91312c586937',
    messagingSenderId: '429952031766',
    projectId: 'mealrecipes-mobileapp-ccc8a',
    storageBucket: 'mealrecipes-mobileapp-ccc8a.firebasestorage.app',
    iosBundleId: 'com.example.mealRecipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUsZ1mXEe5pVqeFFv_kfx7A8eCgsLu8-Q',
    appId: '1:429952031766:ios:73b49f338f91312c586937',
    messagingSenderId: '429952031766',
    projectId: 'mealrecipes-mobileapp-ccc8a',
    storageBucket: 'mealrecipes-mobileapp-ccc8a.firebasestorage.app',
    iosBundleId: 'com.example.mealRecipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP6XPpv4xcihfLySJubR7MnK4lIdQ9zIk',
    appId: '1:429952031766:web:35a3347777f035c8586937',
    messagingSenderId: '429952031766',
    projectId: 'mealrecipes-mobileapp-ccc8a',
    authDomain: 'mealrecipes-mobileapp-ccc8a.firebaseapp.com',
    storageBucket: 'mealrecipes-mobileapp-ccc8a.firebasestorage.app',
    measurementId: 'G-ZBWK1KFF8N',
  );

}